### ISSUE TITLE
Add Splash Text v1.0.0

### ISSUE THREAD

**Issue by StatusZer0** [geode-sdk/indexer#1068] opened 2024-02-18 19:40 UTC
### Your mod link

https://github.com/StatusZer0/Splash-Text/releases/download/Release/statuszer0.splashtext.geode

### Your mod source code

https://github.com/StatusZer0/Splash-Text

### Your mod description

Adds randomized splash text to the title screen.

**Comment by RayDeeUx** [comment] 2024-02-18 20:02
me when the history repeats itself {[the other minecraft splash text mod also took ten tries to submit an issue](https://github.com/geode-sdk/indexer/issues?q=is%3Aissue+minecraft+splash)}

**Comment by StatusZer0** [comment] 2024-02-18 20:17
I failed to use GitHub properly

**Comment by RayDeeUx** [comment] 2024-02-18 20:18
learning curve, statuszer0. it only goes up from here.

**Comment by StatusZer0** [comment] 2024-02-18 20:26
I'm glad. Now I'll be able to hopefully get it up first try with other mods :D

**Comment by Cvolton** [comment] 2024-02-23 17:04
what does this mod do better or different than the other splash mod that already exists

**Comment by ShineUA** [comment] 2024-03-08 17:54
> different splash text. I'll probably make something original though when I can think of something that I can do :P

nah, I already added customization, just use my mod

**Comment by Cvolton** [comment] 2024-03-16 11:46
closing for now, functionally a dupe of an existing mod with no real distinguishing features

**Closed by Cvolton** 2024-03-16 11:46 UTC
